version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    container_name: web
    build: .
    image: node:14
    restart: always
    expose:
      - "4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://database:27017/NotasEscolares
      - PORT=4000
      - NODE_ENV=development
    command: /bin/sh -c 'npm install && npm run dev'

  mongo:
    container_name: database
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    logging:
      driver: "json-file"



volumes:
  mongo_data:
